version: "3"

services:

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: suitecrm
      MYSQL_USER: suitecrm
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    env_file: .env

  importer:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: db
      MYSQL_USER: suitecrm
      MYSQL_DATABASE: suitecrm
    env_file: .env
    stdin_open: true
    tty: true

  crm:
    image: bitnami/suitecrm
    environment:
      MARIADB_HOST: db
      SUITECRM_DATABASE_NAME: suitecrm
      SUITECRM_DATABASE_USER: suitecrm
    env_file: .env
    depends_on:
      - db
    ports:
      - 80:80
      - 443:443
